---
apiVersion: v1
kind: Template
metadata:
  name: powervm-rmc
  annotations:
    description: "powervm-rmc deployment"

parameters:
- description: Project/Namespace
  name: NS
  value: powervm-rmc
- description: Service Account Name
  name: SA
  value: powervm-rmc
- description: Security Context Constraint Name
  name: SCC
  value: powervm-rmc
- description: DaemonSet Name
  name: DS
  value: powervm-rmc
- description: Application Label
  name: LABEL
  value: powervm-rmc

objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${NS}

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SA}
    namespace: ${NS}

- apiVersion: security.openshift.io/v1
  kind: SecurityContextConstraints
  metadata:
    annotations:
      kubernetes.io/description: 'For use by powervm-rmc components.'
    name: ${SCC}
  allowHostDirVolumePlugin: true
  allowHostIPC: true
  allowHostNetwork: true
  allowHostPID: true
  allowHostPorts: true
  allowPrivilegeEscalation: true
  allowPrivilegedContainer: true
  allowedCapabilities:
  - '*'
  allowedUnsafeSysctls:
  - '*'
  defaultAddCapabilities: null
  fsGroup:
    type: RunAsAny
  groups:
  - system:cluster-admins
  - system:nodes
  - system:masters
  priority: null
  readOnlyRootFilesystem: false
  requiredDropCapabilities: null
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  seccompProfiles:
  - '*'
  supplementalGroups:
    type: RunAsAny
  users:
  - system:admin
  - system:serviceaccount:${NS}:${SA}
  volumes:
  - '*'

- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: ${DS}
    namespace: ${NS}
  spec:
    selector:
      matchLabels:
        app: ${LABEL}
    template:
      metadata:
        labels:
          app: ${LABEL}
      spec:
        nodeSelector:
          kubernetes.io/arch: ppc64le
          node.openshift.io/os_id: rhcos
        restartPolicy: Always
        serviceAccountName: ${SA}
        hostNetwork: true
        containers:
          - name: powervm-rmc
            image: 'quay.io/powercloud/rsct-ppc64le:latest'
            ports:
              - name: rmc-tcp
                hostPort: 657
                containerPort: 657
                protocol: TCP
              - name: rmc-udp
                hostPort: 657
                containerPort: 657
                protocol: UDP
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                memory: 1Gi
            volumeMounts:
              - name: lib-modules
                mountPath: /lib/modules
                readOnly: true
            securityContext:
              privileged: true
              runAsUser: 0
        volumes:
          - name: lib-modules
            hostPath:
              path: /lib/modules
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
...
